export const COMPANY = {
  name: 'Reckley Ventures, LLC',
  attention: 'Attn: HELLO KAR',
  state: 'Maryland',
  formed: 'February 24, 2025',
  address: ['100 Middletown Parkway', 'Unit 202 #817', 'Middletown, MD 21769'],
  founder: 'Aaron Reckley',
  domain: 'https://reckleyventures.us',
  effectiveDate: 'July 25, 2026',
  documentVersion: '1.0',
}

export const CONTACT = {
  email: 'support@reckleyventures.us',
  emailHref: 'mailto:support@reckleyventures.us',
  phone: '301-660-6028',
  phoneHref: 'tel:+13016606028',
  general: { label: 'Official contact', address: 'support@reckleyventures.us', active: true },
  legal: { label: 'Legal and privacy', address: 'support@reckleyventures.us', active: true },
  privacy: { label: 'Privacy and account', address: 'support@reckleyventures.us', active: true },
  compliance: { label: 'Compliance', address: 'support@reckleyventures.us', active: true },
  karSupport: { label: 'KAR Support', address: 'support@reckleyventures.us', active: true },
  partnerships: { label: 'Business partnerships', address: 'support@reckleyventures.us', active: true },
}

export const KAR = {
  name: 'KAR',
  url: 'https://hellokar.com',
  category: 'Transportation technology',
  status: 'In development / controlled testing',
  summary: 'A driver-first transportation technology marketplace designed around clearer choices and greater provider control.',
  detail: 'KAR is designed to give independent transportation providers greater control over rates, availability, service areas, and customer relationships—while giving riders clearer choices.',
}

export const EXIT_STRATEGY = {
  name: 'Exit Strategy Cleaning',
  legalOperator: 'Reckley Ventures, LLC operating Exit Strategy Cleaning',
  url: 'https://exitstrategycleaning.com',
  temporaryWebsiteUrl: 'https://exitcleaning-8akvwvwe.manus.space/',
  category: 'Professional Cleaning & Property Services',
  status: 'Operating brand / platform development planned',
  phone: CONTACT.phone,
  phoneHref: CONTACT.phoneHref,
  email: CONTACT.email,
  emailHref: CONTACT.emailHref,
  supportEmail: CONTACT.email,
  effectiveDate: COMPANY.effectiveDate,
  documentVersion: COMPANY.documentVersion,
  mailingAddress: COMPANY.address,
  summary: 'Professional move-out, move-in, deep, recurring, and commercial cleaning services.',
  detail: 'Exit Strategy Cleaning helps homes, property owners, offices, and turnover teams prepare spaces for the next chapter with dependable, detail-focused cleaning services.',
  serviceAreas: ['Washington, DC', 'Maryland', 'Virginia', 'West Virginia', 'Pennsylvania'],
  serviceArea: 'Washington, DC, Maryland, Virginia, West Virginia, and Pennsylvania',
  services: ['Move-out cleaning', 'Move-in cleaning', 'Deep cleaning', 'Recurring residential cleaning', 'Small commercial cleaning'],
  verificationStatus: 'Core service categories and contact details require ongoing owner confirmation; conflicting temporary-site contact claims are not reused.',
  logo: '/exit-strategy-cleaning-logo.png',
  headerLogo: '/exit-strategy-cleaning-header.png',
}

export type LegalSection = { id: string; title: string; body: string[] }

export const EXIT_PRIVACY_SECTIONS: LegalSection[] = [
  { id: 'scope', title: 'Scope', body: [`${EXIT_STRATEGY.name} is a business operated by Reckley Ventures, LLC. This Privacy Policy explains how we collect, use, disclose, retain, and protect information when you visit an Exit Strategy Cleaning website, request a quote, schedule or receive cleaning services, communicate with us, submit service information, or otherwise interact with Exit Strategy Cleaning. It applies to websites, quote requests, booking communications, residential and commercial services, customer support, service-related photographs, contractor or service-provider interactions, invoices and payment records, and privacy requests. Reckley Ventures' corporate website has a separate corporate privacy policy. Any future Exit Strategy Cleaning marketplace may have supplemental privacy disclosures.`] },
  { id: 'customer-information', title: 'Information customers provide', body: ['Depending on the service requested, we may collect your full name, email address, telephone number, service address, billing address, requested service, preferred service date, property type, approximate square footage, rooms and areas to be cleaned, property condition, requested add-ons, access and parking instructions, pet information, special cleaning instructions, messages, photographs submitted for quotes, reviews, feedback, and service complaints. We do not collect every category for every customer.'] },
  { id: 'property-information', title: 'Service and property information', body: ['Customers may provide information about property condition, occupancy status, move-in or move-out dates, landlord or property-manager requirements, excluded areas, delicate surfaces, fragile items, known damage, restricted areas, commercial building requirements, and approved contacts. We use this information to understand the requested scope and coordinate services.'] },
  { id: 'property-access', title: 'Property-access information', body: ['Customers may provide entry instructions, lockbox information, temporary door codes, key pickup instructions, concierge or front-desk instructions, alarm instructions, and parking or loading information. We use property-access information only to coordinate and perform authorized services, protect the property, respond to service issues, and maintain appropriate records. Access information may be shared only with personnel or service providers who reasonably need it for the scheduled service. It is retained only as reasonably necessary for service, recurring access, disputes, safety, fraud prevention, or legal obligations. Do not place unnecessary sensitive information in general comment fields.'] },
  { id: 'service-photographs', title: 'Service photographs', body: ['Exit Strategy Cleaning may collect customer-submitted quote photos, before-service photos, work-in-progress photos, after-service photos, room-by-room completion photos, quality-control photos, photographs documenting pre-existing damage, and photographs documenting safety or service concerns. Service photographs may be used to verify property condition, document the agreed scope, confirm completion, support quality control, address customer concerns, protect customers and service personnel, and resolve disputes. We do not use photographs from inside a customer\'s property for public advertising or promotional purposes without separate permission.', 'We make reasonable efforts to avoid unnecessarily capturing faces, private documents, financial records, computer screens, medications, personal photographs, security information, and other sensitive belongings. Incidental personal items may nevertheless appear.'] },
  { id: 'service-personnel', title: 'Information about service personnel', body: ['Where applicable, we may collect identity and contact information, service availability, service area, tax and payment information, work records, arrival and departure times, check-in data, service photographs, quality and customer-feedback records, insurance or credential information where required, and device or technical information used for work systems. Services may be performed by assigned personnel or independent service providers. We do not state that background checks are performed unless separately communicated.'] },
  { id: 'automatic', title: 'Automatically collected information', body: ['We may receive IP address, browser type, device type, operating system, referring page, pages viewed, approximate location inferred from IP, date and time, technical logs, form-submission metadata, and security and error information. The corporate site is not configured with Google Analytics, Google Tag Manager, Meta Pixel, Google Ads, reCAPTCHA, embedded maps, chat widgets, payment embeds, or advertising pixels. Essential hosting and security logs may still be processed by infrastructure providers.'] },
  { id: 'use', title: 'How information is used', body: ['We use information to respond to inquiries; prepare estimates or quotes; schedule, assign, and perform services; communicate arrival or service updates; process payments; issue invoices and receipts; document job completion; perform quality control; handle complaints and re-clean requests; investigate damage or safety concerns; prevent fraud; enforce agreements; maintain accounting and tax records; improve services; comply with law; and protect customers, personnel, property, and the business.'] },
  { id: 'payments', title: 'Payments', body: ['Payments may be processed by third-party payment processors. When payment details are entered directly into a processor\'s secure system, Exit Strategy Cleaning does not intentionally store complete card numbers. Card, ACH, commercial invoicing, and approved Net 10 terms may be available where offered or approved.'] },
  { id: 'disclosure', title: 'Disclosure of information', body: ['Information may be disclosed to personnel or service providers assigned to the work; scheduling and CRM providers; website, hosting, and storage providers; payment and communication providers; accounting and professional advisers; insurers where applicable; fraud and safety providers; law enforcement or regulators when legally required; parties involved in a legitimate corporate transaction; and other parties with consent. We do not sell personal information for money.'] },
  { id: 'retention', title: 'Data retention', body: ['We retain information for as long as reasonably necessary for the purposes described in this policy, including providing services, maintaining business and accounting records, addressing disputes, documenting property condition, preventing fraud, satisfying tax and insurance requirements, and complying with law.'] },
  { id: 'rights', title: 'Privacy rights and requests', body: ['Where applicable, individuals may request access, correction, deletion, information about use and disclosure, withdrawal from marketing communications, opt-out of sale or targeted advertising if those practices are used, and appeal of a denied qualifying privacy request where required. Identity verification may be required. No individual will be discriminated against for exercising an applicable privacy right. Submit a request at the privacy request page.'] },
  { id: 'marketing', title: 'Marketing and communications', body: ['Quote responses, appointment communications, arrival notices, invoices, and service follow-up are transactional. Promotional email and text messaging are optional communications and are not sent merely because someone requested a quote. Commercial email will include accurate sender identification, an appropriate postal address, and a functional opt-out process.'] },
  { id: 'children', title: 'Children', body: ['Exit Strategy Cleaning websites and booking services are intended for adults arranging property services. They are not directed to children.'] },
  { id: 'security', title: 'Security', body: ['We use administrative, technical, and organizational safeguards designed to protect personal information. No storage or transmission system can be guaranteed to be completely secure.'] },
  { id: 'changes-contact', title: 'Changes and contact', body: [`Updated versions will be posted with a revised effective date and version. Contact ${EXIT_STRATEGY.email} or ${EXIT_STRATEGY.phone} with privacy questions.`, `Reckley Ventures, LLC\nOperating Exit Strategy Cleaning\n${COMPANY.attention}\n${COMPANY.address.join('\n')}`] },
]

export const EXIT_WEBSITE_TERMS_SECTIONS: LegalSection[] = [
  { id: 'acceptance', title: 'Acceptance', body: ['These Terms of Use govern access to and use of Exit Strategy Cleaning websites and informational content. Exit Strategy Cleaning is operated by Reckley Ventures, LLC. Using the website constitutes acceptance of these Website Terms. Submitting a quote request alone does not create a booking or service contract.'] },
  { id: 'informational', title: 'Informational purpose', body: ['Website content is provided for general information. Services, availability, pricing, service areas, and scheduling may change.'] },
  { id: 'quotes', title: 'Quotes', body: ['A quote request is a request for information and is not a confirmed appointment. A service is booked only when Exit Strategy Cleaning provides written confirmation or otherwise confirms the appointment through an authorized booking process.'] },
  { id: 'accurate', title: 'Accurate information', body: ['Users must provide reasonably accurate contact details, address, property details, service scope, condition information, and access instructions. Inaccurate or incomplete information may affect price, timing, or availability. Booked services are governed by the Cleaning Service Terms.'] },
  { id: 'intellectual-property', title: 'Intellectual property', body: ['The Exit Strategy Cleaning name, logos, website copy, photographs owned by the business, graphics, designs, software, forms, and service materials are protected by applicable law. These terms do not claim ownership of customer-submitted photos.'] },
  { id: 'prohibited', title: 'Prohibited use', body: ['Do not use the website unlawfully; interfere with its operation; impersonate another person; submit false quote requests; harvest data; attempt unauthorized access; upload malware or infringing content; or use content to misrepresent affiliation.'] },
  { id: 'third-party', title: 'Third-party links', body: ['Third-party sites have separate policies. Exit Strategy Cleaning is not responsible for their independent content or practices.'] },
  { id: 'availability', title: 'Availability and disclaimer', body: ['The website may contain errors, omissions, or interruptions. We do not guarantee service availability, exact arrival, or acceptance of every project. Nothing here disclaims obligations that cannot legally be disclaimed.'] },
  { id: 'liability', title: 'Website limitation', body: ['To the maximum extent permitted by law, Reckley Ventures, LLC and Exit Strategy Cleaning will not be liable for indirect, incidental, special, or consequential losses resulting solely from use of the informational website. This website clause does not limit valid claims arising from an actual cleaning service; those belong in the Service Terms.'] },
  { id: 'future', title: 'Future marketplace', body: ['Future software, customer accounts, provider subscriptions, or marketplace services may have separate agreements. The future marketplace is not currently active.'] },
  { id: 'law-contact', title: 'Governing law and contact', body: [`Maryland law governs these terms, subject to applicable consumer-protection laws. Contact ${EXIT_STRATEGY.email} or ${EXIT_STRATEGY.phone}.` ] },
]

export const CLEANING_SERVICE_TERMS_SECTIONS: LegalSection[] = [
  { id: 'booking', title: 'Booking and confirmation', body: ['These Service Terms apply when a customer requests, schedules, purchases, or receives cleaning services arranged or provided under the Exit Strategy Cleaning brand, operated by Reckley Ventures, LLC. A request is not confirmed until accepted in writing, by approved electronic confirmation, or through an authorized booking system.'] },
  { id: 'estimates', title: 'Estimates and quotes', body: ['An estimate may be based on customer-provided information and may change if property size, condition, scope, access, or requested services materially differ. Fixed quotes must be identified as fixed in writing. Add-ons and change orders require approval. Taxes or processor charges apply only when properly disclosed. Exit Strategy Cleaning will communicate material price changes before performing materially expanded work whenever reasonably practical.'] },
  { id: 'scope', title: 'Scope of service', body: ['The scope is based on the written quote, booking confirmation, checklist, or commercial agreement. Services not expressly included are excluded.'] },
  { id: 'unsafe-conditions', title: 'Conditions outside ordinary cleaning', body: ['Exit Strategy Cleaning may decline, stop, restrict, or reprice work involving biohazards; bodily fluids beyond ordinary household cleaning; uncontrolled mold; active pest infestations; needles or sharps; illegal substances; dangerous chemicals; fire or flood damage; heavy construction debris; hoarding conditions; unsafe structures; inaccessible areas; aggressive animals; unsecured weapons; or conditions posing unreasonable health or safety risks. Exit Strategy Cleaning is not represented as a certified mold, biohazard, pest-control, or hazardous-material remediation provider unless separately approved.'] },
  { id: 'preparation', title: 'Customer property-preparation responsibilities', body: ['Customers should remove or secure valuables, cash, jewelry, medications, financial documents, firearms, and sensitive materials; identify fragile or irreplaceable items; remove excessive clutter where needed; provide electricity and running water; disclose delicate finishes and known damage; identify areas that must not be entered; arrange safe parking and lawful access; secure or disclose pets; and provide an authorized contact.'] },
  { id: 'access', title: 'Access', body: ['The customer is responsible for legal and timely access, including keys, lockboxes, codes, concierge access, parking, gated communities, and commercial security requirements. No no-access or lockout charge will apply unless the possibility and amount or calculation method were disclosed before booking.'] },
  { id: 'arrival', title: 'Arrival windows', body: ['Arrival times may be provided as windows rather than exact guarantees. Reasonable delays may result from traffic, weather, prior-job conditions, building access, emergencies, or safety concerns. We will communicate where reasonably possible.'] },
  { id: 'personnel-conduct', title: 'Service personnel and customer conduct', body: ['Services may be performed by personnel or service providers assigned or authorized by Exit Strategy Cleaning. Customers must provide a safe, lawful, harassment-free environment. We may refuse or terminate service for threats, harassment, discrimination, unsafe conditions, illegal activity, aggressive animals, interference with safe work, or requests outside lawful cleaning services.'] },
  { id: 'photos-property', title: 'Property photographs and valuables', body: ['The separate Photo Documentation Policy applies. Interior property photos will not be used for public marketing without separate permission. Customers should secure valuables and disclose fragile or high-value items. Personnel should not be required to handle cash, jewelry, collectibles, firearms, controlled medication, or confidential records without prior written agreement.'] },
  { id: 'damage', title: 'Pre-existing damage and damage concerns', body: ['Normal cleaning may reveal discoloration, wear, loose fixtures, failing caulk, damaged finishes, worn paint, stains, improperly installed items, or weakened materials. Service photos may document pre-existing conditions. Customers should report suspected damage promptly with reasonable details. Exit Strategy Cleaning will have a reasonable opportunity to inspect and investigate.'] },
  { id: 'satisfaction', title: 'Satisfaction and re-clean requests', body: ['If a customer believes an agreed service area was materially missed, the customer should contact Exit Strategy Cleaning promptly and provide reasonable details. We may review job records, photographs, the approved scope, and property conditions and may offer a reasonable re-clean or other resolution when appropriate. Move-out cleaning does not guarantee the return of a security deposit, a landlord\'s approval, a property sale, or satisfaction of requirements that were not included in the agreed scope.'] },
  { id: 'recurring-commercial', title: 'Recurring and commercial services', body: ['Recurring schedules remain subject to availability; scope may change; customers must provide continuing access; skipped visits may affect the next service condition; pricing may be adjusted with advance notice; and cancellation of recurring service does not automatically cancel unpaid completed work. Commercial agreements may separately cover frequency, approved contacts, scopes, keys, badges, confidentiality, invoices, ACH, card payment, approved Net 10 terms, change orders, and security requirements. A signed commercial agreement controls if it conflicts with these general terms for that service.'] },
  { id: 'payment', title: 'Payment', body: ['Payment timing and method are shown in the quote, booking confirmation, invoice, or commercial agreement. Card, ACH, invoice, and approved Net 10 terms may be available where offered. Returned payments, chargebacks, or overdue invoices may lead to service suspension and lawful collection activity. No undisclosed fee will be imposed.'] },
  { id: 'cancellation-refunds', title: 'Cancellations and refunds', body: ['The separate Cancellation, Rescheduling, and No-Access Policy applies. No cancellation, rescheduling, lockout, or no-access fee will be charged unless the fee or its method of calculation was disclosed to the customer before booking. Completed cleaning work is generally addressed through inspection, documentation, and reasonable resolution. Unused deposits or prepaid amounts are handled according to written booking terms and applicable law.'] },
  { id: 'events', title: 'Events outside control', body: ['Severe weather, unsafe travel, utility outage, building closure, emergency, government restriction, illness, labor or technology disruption, or another event reasonably outside control may require rescheduling or interruption.'] },
  { id: 'disputes-law', title: 'Disputes and governing law', body: ['Before commencing formal legal proceedings, the parties are encouraged to provide written notice of the dispute and make a good-faith effort to resolve it. These terms do not add mandatory arbitration or a class-action waiver. Maryland law applies, subject to applicable consumer-protection law. Nothing waives liability for gross negligence, intentional misconduct, or rights that cannot be waived.'] },
]

export const EXIT_CANCELLATION_SECTIONS: LegalSection[] = [
  { id: 'contact', title: 'Contact promptly', body: [`Customers should contact ${EXIT_STRATEGY.email} or ${EXIT_STRATEGY.phone} as soon as possible to cancel or reschedule.`] },
  { id: 'reschedule', title: 'Rescheduling', body: ['Rescheduling is subject to availability. Cancellation terms disclosed in the booking confirmation control.'] },
  { id: 'fees', title: 'Fees and deposits', body: ['No fee is imposed unless it was disclosed before booking. Deposits, when required, are handled according to the written booking terms. No-access situations may be treated as late cancellation only when previously disclosed.'] },
  { id: 'business', title: 'Business rescheduling', body: ['Exit Strategy Cleaning may reschedule for weather, safety, illness, building closure, or emergency and will notify customers when reasonably possible. Commercial agreements may contain separate terms.'] },
]

export const EXIT_PHOTO_SECTIONS: LegalSection[] = [
  { id: 'purpose', title: 'Purpose and permitted uses', body: ['Photos may be taken for quotes, job completion, property condition, quality control, safety, customer concerns, and dispute resolution. Customer-submitted photos may be used to prepare quotes.'] },
  { id: 'access', title: 'Access and restrictions', body: ['Personnel assigned to the work and authorized business personnel may access photos for these purposes. Service personnel must not post customer-property photos on personal social media or use them for unrelated personal purposes.'] },
  { id: 'privacy', title: 'Privacy and marketing', body: ['Reasonable efforts will be made to minimize incidental personal belongings. Public marketing requires separate permission. Requests to limit nonessential photography will be considered where practical, but necessary condition, safety, completion, or dispute documentation may still be required.'] },
  { id: 'retention', title: 'Retention', body: ['Photos are retained according to business, legal, accounting, insurance, safety, and dispute needs.'] },
]

export const EXIT_ACCESS_SECTIONS: LegalSection[] = [
  { id: 'information', title: 'Access information covered', body: ['This policy covers keys, lockboxes, temporary or permanent codes, alarm instructions, building badges, concierge instructions, commercial credentials, and gated-community access.'] },
  { id: 'authorized', title: 'Authorized access', body: ['Customers must have authority to provide access. Access data is used only for authorized service purposes and shared only with people who reasonably need it. Customers should provide temporary codes when practical and disable them after service.'] },
  { id: 'security', title: 'Security practices', body: ['Exit Strategy Cleaning does not guarantee compatibility with every smart-lock or building system. Lost keys, failed access, or security concerns should be reported promptly. Public forms should not collect unnecessary permanent security credentials. Customers should not send codes through unapproved public channels.'] },
]

export const PRIVACY_SECTIONS: LegalSection[] = [
  { id: 'scope', title: 'Scope and company', body: ['This policy describes how Reckley Ventures, LLC, doing business as KAR where applicable, may collect and use information in connection with KAR rider, driver/provider, website, support, and administrative interactions. It is written conservatively for review before commercial launch.'] },
  { id: 'collected', title: 'Information collected', body: ['KAR may collect names, email addresses, telephone numbers, account credentials, rider profiles, provider business profiles, identity-verification information, driver and vehicle documents, insurance and registration information, profile and verification photographs, communications, support interactions, ratings, reviews, device information, logs, diagnostics, payment and transaction metadata, subscription information, promotion and referral attribution, safety reports, and fraud or risk signals.', 'Where provider onboarding requires screening, KAR may process consumer-reporting or screening information and related FCRA disclosures and authorizations through appropriate vendors.'] },
  { id: 'location', title: 'Location information', body: ['KAR may use foreground and precise location to support ride requests, pickup and destination coordination, navigation, trip status, safety functions, and provider availability. For eligible provider activity, background location may be used while a provider is online, en route, or participating in a ride, including ride restoration and safety functionality. KAR does not describe background location as continuous while a provider is offline unless that behavior is confirmed.', 'Users can manage location permissions through device settings. Turning off a permission may limit parts of the service.'] },
  { id: 'payments', title: 'Payments and subscriptions', body: ['Payment-card or banking information may be processed by third-party payment providers such as Stripe. KAR may receive payment confirmations, limited payment details, transaction metadata, subscription information, and records needed for support, accounting, fraud prevention, and legal compliance. This policy does not claim that Reckley Ventures stores full card numbers.'] },
  { id: 'sharing', title: 'How information may be shared', body: ['KAR may share information as needed with service providers supporting identity verification, screening, payments, mapping and navigation, SMS/email/push communications, cloud hosting and storage, customer support, fraud and safety operations, analytics, legal compliance, and corporate transactions. Information may also be disclosed when required by law or to protect users, the public, KAR, or its rights.'] },
  { id: 'retention', title: 'Retention', body: ['KAR does not publish fixed retention periods here. Categories of information may be retained as needed for legal compliance, safety, fraud prevention, tax and accounting, dispute handling, insurance, regulatory obligations, and enforcement of agreements.'] },
  { id: 'choices', title: 'Choices and rights', body: [`Depending on applicable law, users may request access, correction, deletion, or other rights. Users may manage location permissions, notifications, marketing preferences, and SMS opt-outs where applicable. Privacy requests may be sent to ${CONTACT.email}. See the account deletion page for additional instructions.`] },
  { id: 'children', title: 'Children and security', body: ['KAR is not intended for users below the approved minimum age established in KAR’s account rules. The final age threshold must be confirmed before publication. We use administrative, technical, and organizational safeguards designed to protect information, but no system can be guaranteed secure.'] },
  { id: 'changes', title: 'Changes and contact', body: [`This policy may be updated as KAR evolves. The effective date and document version will be updated when a final policy is approved. Questions may be sent to ${CONTACT.email}.`] },
]

export const TERMS_SECTIONS: LegalSection[] = [
  { id: 'role', title: 'KAR’s role', body: ['KAR is a transportation technology marketplace operated by Reckley Ventures, LLC. It helps riders discover and request transportation services offered by independent transportation providers. KAR is not the transportation provider and does not represent independent providers as employees.'] },
  { id: 'choice', title: 'Provider settings and rider choice', body: ['Independent providers may configure rates and business settings, subject to applicable marketplace rules. Riders may compare provider-specific choices or use Quick Match where available. Market availability varies and no ride, quote, reservation, or response is guaranteed.'] },
  { id: 'eligibility', title: 'Eligibility and accounts', body: ['Users must meet applicable age, geographic, identity, and other eligibility requirements. Account holders are responsible for accurate information, account security, and activity performed through their accounts.'] },
  { id: 'payments', title: 'Payments, subscriptions, and promotions', body: ['Accepted quotes and scheduled reservations may become binding under published rules. KAR may charge subscription or software fees to providers. Core transportation commission is currently structured as 0%, subject to published terms; payment processing and other third-party fees may apply. Provider transportation revenue is distinct from KAR subscription revenue.', 'Promotions funded by KAR do not reduce provider gross unless an expressly provider-funded program is voluntarily accepted. Referrals and promotions may be inactive or subject to campaign terms. Unreleased or unfinished payment behavior is not promised by these terms.'] },
  { id: 'safety', title: 'Safety and acceptable use', body: ['Users must use KAR lawfully and respectfully, follow safety instructions, and not misuse the marketplace, interfere with the service, impersonate others, harass, defraud, or submit unlawful content. KAR is not an emergency service. Call 911 or the appropriate local emergency service when immediate assistance is required.'] },
  { id: 'ip', title: 'Intellectual property', body: ['KAR and its licensors retain rights in the service, software, branding, content, and related intellectual property. These terms grant only the limited rights needed to use the service as intended.'] },
  { id: 'legal', title: 'Disclaimers, disputes, and termination', body: ['The service may be unavailable or contain errors. Transportation is provided by independent providers. Warranty disclaimers, limitation of liability, dispute-resolution, governing-law, and termination provisions apply as stated in the current KAR service agreements and applicable law.'] },
  { id: 'contact', title: 'Contact', body: [`Questions may be sent to ${CONTACT.email}.`] },
]
